<a href="https://colab.research.google.com/github/Kadergueli/conflict-risk-analysis-chad/blob/main/03_exploratory_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/ACLED_CHAD_RESEARCH/data/cleaned_acled_chad.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
df.shape

(558, 14)

In [4]:
df.columns

Index(['EVENT_DATE', 'YEAR', 'TIME_PRECISION', 'EVENT_TYPE', 'INTERACTION',
       'COUNTRY', 'ADMIN1', 'ADMIN2', 'ADMIN3', 'LOCATION', 'LATITUDE',
       'LONGITUDE', 'GEO_PRECIS', 'FATALITIES'],
      dtype='object')

In [5]:
df.head()

,EVENT_DATE,YEAR,TIME_PRECISION,EVENT_TYPE,INTERACTION,COUNTRY,ADMIN1,ADMIN2,ADMIN3,LOCATION,LATITUDE,LONGITUDE,GEO_PRECIS,FATALITIES
0,15/02/1997,1997,3,Violence against civilians,17,Chad,Logone Oriental,Nya Pendé,Mbaikoro,Moundou,"8,56670","16,08330",1,0
1,15/02/1997,1997,3,Violence against civilians,27,Chad,Logone Oriental,Nya Pendé,Kaba-Donia,Donia,"8,40509","16,42309",1,1
2,15/02/1997,1997,3,Violence against civilians,27,Chad,Logone Oriental,Lanya,Mbikou,Mbikou,"8,60141","16,39258",1,2
3,15/07/1997,1997,3,Battle-No change of territory,12,Chad,Guéra,Guéra,Mousmare,Bose,"11,07000","17,83000",2,40
4,24/07/1997,1997,2,Violence against civilians,37,Chad,Moyen-Chari,Lac Iro,Boum-Kebir,Boum-Kabir,"10,18000","19,39000",1,0

In [6]:
# évènements par regions
df['ADMIN1'].value_counts()

ADMIN1
Ouaddaï               210
Ville de N'Djamena    109
Bet                    80
Wadi Fira              59
Logone Oriental        17
Salamat                15
Kanem                  12
Moyen-Chari            11
Guéra                  11
Mayo-Kebbi Est          6
Batha                   5
Logone Occidental       5
Mandoul                 4
Mayo-Kebbi Ouest        4
Hadjer-Lamis            4
Lac                     3
Chari-Baguirmi          3
Name: count, dtype: int64

In [7]:
# regroupé par regions et les fatalités
df.groupby('ADMIN1')['FATALITIES'].sum().sort_values(ascending=False)

ADMIN1
Ouaddaï               2210
Bet                   1438
Wadi Fira              593
Ville de N'Djamena     517
Salamat                428
Kanem                  261
Logone Oriental        163
Guéra                   72
Batha                   59
Moyen-Chari             51
Hadjer-Lamis            36
Mayo-Kebbi Ouest        15
Logone Occidental       12
Lac                      6
Chari-Baguirmi           4
Mandoul                  2
Mayo-Kebbi Est           2
Name: FATALITIES, dtype: int64

In [8]:
#evenements dominants
df['EVENT_TYPE'].value_counts()

EVENT_TYPE
Battle-No change of territory                 243
Violence against civilians                    181
Battle-Non-state actor overtakes territory     36
Riots/Protests                                 30
Remote violence                                24
Non-violent activity by a conflict actor       21
Battle-Government regains territory            18
Non-violent transfer of territory               5
Name: count, dtype: int64

In [9]:
#evolution par annee
df.groupby('YEAR').size()

YEAR
1997     15
1998     12
1999     12
2000     22
2001     11
2002     15
2003     14
2004     36
2005     43
2006    119
2007    103
2008     76
2009     23
2010     11
2011      6
2012      7
2013      6
2014     27
dtype: int64